# -*- coding: utf-8 -*-
"""Code Solutions to Quiz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QeyBYJHbM4D-6h9fvn4Fv2irR2LSdLHz
"""

import pandas as pd
df = pd.read_csv(r"https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv")
df

df.sample(10)

df.sample(10)

df['fuel_type_code_pudl'].value_counts()

df['report_year'].value_counts()

df['report_year'][df_bool].value_counts()

df_bool = df['fuel_type_code_pudl'] == 'coal'
df[df_bool]

df[df_bool][['report_year','fuel_type_code_pudl','fuel_cost_per_unit_burned']]

df_bool1 = df['report_year'] == 1994
df[df_bool1]

df_desc = df[df_bool][['report_year','fuel_type_code_pudl','fuel_cost_per_unit_burned']]
df_desc

sthh = df['report_year'][df_bool]
sthh.value_counts()
sthh.searchsorted(value=)

df['fuel_mmbtu_per_unit'].describe()

df['report_year'].value_counts()

_c# this sums all the null values in each column

df.isnull().sum()

# to get the sum of the null values
df.isnull().values.sum()

# i was just playing around here oo ;) dont know what this code means

df.isnull().values

df.corr()

df.to_excel(r'C:\Users\HP\Documents\HamoyeTwo.xlsx', index = False)

df.shape